# Generated by Django 4.0.2 on 2023-04-13 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0008_customerreview_product_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerreview',
            options={'ordering': ['-id']},
        ),
    ]
