# Generated by Django 4.0.2 on 2023-04-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0009_alter_customerreview_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='best_rating_number_of_orange_stars',
            field=models.IntegerField(default=0),
        ),
    ]
