# Generated by Django 4.0.2 on 2023-04-20 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0011_alter_customerreview_date_and_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerreview',
            name='date_and_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
