# Generated by Django 4.0.2 on 2023-05-02 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0016_cart_customer_alter_cart_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='best_rating_number_of_orange_stars',
            new_name='number_of_orange_stars',
        ),
    ]
