# Generated by Django 4.0.2 on 2023-05-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0017_rename_best_rating_number_of_orange_stars_product_number_of_orange_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='session_id',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
    ]
