# Generated by Django 4.0.2 on 2023-03-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='sdkjkjfsd'),
            preserve_default=False,
        ),
    ]
