# Generated by Django 4.0.2 on 2023-04-08 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0006_customerreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerreview',
            name='date_and_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customerreview',
            name='number_of_orange_stars',
            field=models.IntegerField(default='12'),
            preserve_default=False,
        ),
    ]
