# Generated by Django 4.0.2 on 2023-04-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0007_customerreview_date_and_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerreview',
            name='product_name',
            field=models.CharField(default='1', max_length=1000),
            preserve_default=False,
        ),
    ]
