# Generated by Django 4.0.2 on 2023-04-20 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0010_product_best_rating_number_of_orange_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerreview',
            name='date_and_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
