# Generated by Django 4.0.2 on 2023-04-22 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0014_cart_quantity_alter_cart_image_alter_cart_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
    ]
